apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: apps
  name: producer
  labels:
    app: producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
      - name: producer
        image: ada-orchestration-app_producer:latest